USE SENAI;
GO

CREATE FUNCTION FUNC_DEP(@nomeDep VARCHAR(200))
RETURNS TABLE
AS
RETURN
(
 SELECT nomeFunc AS Funcionario,nomeDep AS Departamento FROM FUNCIONARIO
 INNER JOIN DEPARTAMENTOS
 ON FUNCIONARIO.idDep = DEPARTAMENTOS.idDep
 WHERE nomeDep LIKE '%'+@nomeDep+'%'
)
GO

SELECT * FROM FUNC_DEP('T.I');

