CREATE DATABASE SENAI;
GO

USE SENAI;
GO

CREATE TABLE DEPARTAMENTOS(
 idDep TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeDep VARCHAR(200) NOT NULL
);
GO

CREATE TABLE FUNCIONARIO(
 idFunc SMALLINT PRIMARY KEY IDENTITY(1,1),
 idDep TINYINT FOREIGN KEY REFERENCES DEPARTAMENTOS(idDep),
 nomeFunc VARCHAR(50) NOT NULL,
 dataNasc DATE NOT NULL
);
GO
