CREATE DATABASE BOLETIM;
GO

USE BOLETIM;
GO

CREATE TABLE NOTAS(
 idNotas SMALLINT PRIMARY KEY IDENTITY(1,1),
 nota1 SMALLINT NOT NULL,
 nota2 SMALLINT NOT NULL,
 nota3 SMALLINT NOT NULL
);
GO

CREATE TABLE ALUNOS(
 idAlunos SMALLINT PRIMARY KEY IDENTITY(1,1),
 idNotas SMALLINT FOREIGN KEY REFERENCES NOTAS(idNotas),
 nomeAluno VARCHAR(50) NOT NULL,
 dataNasc DATE NOT NULL
);
GO

